import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import Sidebar from "@/components/shared/Dashboard Sidebar/Sidebar";
import { AdminDashboardWrapper } from "@/components/Wrapper Components/Admin Dashboard Wrapper/AdminDashboardWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cloth Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <AdminDashboardWrapper>{children}</AdminDashboardWrapper>
    </div>
  );
}
