import type { Metadata } from "next";
import { Inter, Josefin_Sans, Poppins, Ubuntu } from "next/font/google";
import "@/app/globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import Footer from "@/components/shared/footer/footer";
import CustomWrapper from "@/components/Custom Wrapper/CustomWrapper";
import { Toaster } from "@/components/ui/toaster";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/NextAuth/authOptions";
import ReduxProvider from "@/utils/Redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "500", "700", "800"],
});

export const ubuntu = Ubuntu({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});
export const joseph = Josefin_Sans({
  variable: "--font-ubuntu",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Pharmasia",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={ubuntu.className}>
          <Navbar />
          <div className="min-h-screen mx-auto">
            <CustomWrapper>{children}</CustomWrapper>
          </div>
          <Footer />
          <Toaster />
        </body>
      </html>
    </ReduxProvider>
  );
}
